-- NUCLEAR OPTION: Disable ALL RLS to make the app work
-- You can add security back later once it's functional

-- Disable RLS on ALL tables
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE bands DISABLE ROW LEVEL SECURITY;
ALTER TABLE band_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE song_suggestions DISABLE ROW LEVEL SECURITY;
ALTER TABLE song_votes DISABLE ROW LEVEL SECURITY;
ALTER TABLE song_ratings DISABLE ROW LEVEL SECURITY;
ALTER TABLE rehearsals DISABLE ROW LEVEL SECURITY;
ALTER TABLE rehearsal_setlists DISABLE ROW LEVEL SECURITY;
ALTER TABLE vote_rate_limits DISABLE ROW LEVEL SECURITY;
ALTER TABLE song_discussions DISABLE ROW LEVEL SECURITY;
ALTER TABLE song_metadata DISABLE ROW LEVEL SECURITY;

-- Grant full permissions to authenticated users
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO authenticated;